spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mess?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
      username: mess
      password: mess
    devtools:
      livereload:
        enabled: true
        # thymeleaf cache 비활성화
    thymeleaf:
      cache: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true
